### ISSUE TITLE
1.4.1: `secure-blocks-for-gutenberg-admin` CSS handle is enqueued to leak outside of block editor screens 

### ISSUE THREAD

**Issue by lkraav** [mwtsn/secure-blocks-for-gutenberg#1]
All non-block-editor screens will have `wp-blocks` dependency missing, which https://github.com/johnbillion/query-monitor will highlight.

![image](https://user-images.githubusercontent.com/147228/51435436-dba2b600-1c3c-11e9-967b-a97cb1853ea2.png)

Recommended action:

1. Install Query Monitor as permanent part of developer workflow
2. Only enqueue `secure-blocks-for-gutenberg-admin` styles on block editor screen

Your thoughts?

**Comment by mattwatsoncodes** [comment]
Hi @lkraav thank you for this. It should now be patched with the latest version.
